"""add document file metadata

Revision ID: e88fcb8bd5c0
Revises: 24c4e93ddea7
Create Date: 2026-08-18 17:48:12.756997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88fcb8bd5c0'
down_revision: Union[str, Sequence[str], None] = '24c4e93ddea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
