# `operator.add` combines old and new conversation-message lists.
import operator

# UUID is used for optional document identifiers.
import uuid

# Annotated attaches LangGraph's list-combining rule to a field.
# Literal restricts route choices.
# TypedDict describes the state structure.
from typing import Annotated, Literal, TypedDict


class RAGState(TypedDict, total=False):
    """
    Shared information passed between LangGraph workflow nodes.
    """

    # The current question entered by the user.
    question: str

    # Optional document selected by the user.
    document_id: uuid.UUID | None

    # Conversation messages stored for this LangGraph thread.
    #
    # `operator.add` tells LangGraph to append new messages to the
    # existing history instead of replacing the entire list.
    conversation_history: Annotated[
        list[dict[str, str]],
        operator.add,
    ]

    # Numerical representation of the current question.
    query_vector: list[float]

    # Relevant PDF chunks returned by Qdrant.
    document_sources: list[dict]

    # Decision produced by the routing node.
    route: Literal["document", "web", "both"]

    # Results returned by live web search.
    web_sources: list[dict]

    # Final answer generated by Gemini.
    answer: str

    # Readable workflow error, if one occurs.
    error: str